services:
  postgres:
    image: postgres:14
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=123456
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
      - "-c"
      - "log_statement=mod"

